### ISSUE TITLE
AWS Hesabı olmadan çalıştırmak

### ISSUE THREAD

**Issue by myuksektepe** [abdurrahmanekr/tdk-service#1]
Merhaba,

Bir AWS hesabına sahip olmadan kendi sunucumda nasıl çalıştırabilirim?

**Comment by abdurrahmanekr** [comment]
Uygulamayı başında express ile çalışır olarak tasarlamıştım. Bu [commit'te](https://github.com/abdurrahmanekr/tdk-service/commit/8fc36715bd4dada9eb667bc01cc3598bf67a521d) kodları mevcut. 
Şöyle yapın. Projeyi clone yapın.

```
$ git clone https://github.com/abdurrahmanekr/tdk-service
$ cd tdk-service
```
Sonra dediğim commit'e geçiş yapın.
```
git checkout 8fc36715bd4dada9eb667bc01cc3598bf67a521d
```
Sonra bağımlılıkları kurun
```
npm install
```
Projeyi başlatın
```
npm start
```
Sonra tarayıcında `http://localhost:1071/getWord/{istediğiniz kelime}` şeklinde istek attığınızda servis çalışacaktır.
